#
# This file is downloaded via the robotpy-sphinx-plugin, and converted
# into a usable sidebar.
#
# This is a downloaded dependency because it's really annoying to make commits
# to all of the projects each time we want to change the sidebar.
#

[projects]
teak = "https://teak.readthedocs.io"
unity = "https://teak.readthedocs.io/projects/unity"
air = "https://teak.readthedocs.io/projects/air"
server = "https://teak.readthedocs.io/projects/server-api"

[[toctree]]
name = "User Guides"
items = [
    {p="teak", k="Getting Started", v="getting_started"},
    {p="teak", k="Tips and Tricks", v="tips_and_tricks"},
    {p="teak", k="Reference", v="reference"},
]

[[toctree]]
name = "Developer Guides"
items = [
    {p="unity", k="Unity SDK", v="index"},
    {p="air", k="Adobe AIR SDK", v="index"},
    {p="server", k="Server API", v="index"},
]
